# Generated by Django 3.1 on 2020-09-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_auto_20200917_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='in_scrum',
            field=models.BooleanField(default=False),
        ),
    ]
